import { NgModule} from '@angular/core'
import { DragDropModule } from '@angular/cdk/drag-drop';


import { 
   MatDatepickerModule,
   MatNativeDateModule,
   MatSliderModule,
   MatMenuModule,
   MatIconModule,
   MatCardModule,
   MatButtonModule,
   MatStepperModule,
   MatFormFieldModule,
   MatInputModule,
   MatSelectModule,
   MatProgressBarModule,
   MatDividerModule,
   MatPaginatorModule,
   MatSortModule,
   MatTableModule,
   MatTooltipModule,
   MatDialogModule,
   MatSnackBarModule,
   MatListModule,
   MatTreeModule,
   MatCheckboxModule,
   MatRadioModule,
   MatExpansionModule,
   MatSlideToggleModule,
   MatTabsModule,
   MatChipsModule,
   MatProgressSpinnerModule,
 } from '@angular/material';

@NgModule({
   imports: [
      MatDatepickerModule,
      MatNativeDateModule,
      MatSliderModule,
      MatMenuModule,
      MatIconModule,
      MatCardModule,
      MatButtonModule,
      MatStepperModule,
      MatFormFieldModule,
      MatInputModule,
      MatSelectModule,
      MatProgressBarModule,
      MatDividerModule,
      MatPaginatorModule,
      MatSortModule,
      MatTableModule,
      MatTooltipModule,
      MatDialogModule,
      MatSnackBarModule,
      MatListModule,
      MatTreeModule,
      MatCheckboxModule,
      MatRadioModule,
      DragDropModule,
      MatExpansionModule,
      MatSlideToggleModule,
      MatTabsModule,
      MatChipsModule,
      MatProgressSpinnerModule,
   ],
   exports: [
      MatDatepickerModule,
      MatNativeDateModule,
      MatSliderModule,
      MatMenuModule,
      MatIconModule,
      MatCardModule,
      MatButtonModule,
      MatStepperModule,
      MatFormFieldModule,
      MatInputModule,
      MatSelectModule,
      MatProgressBarModule,
      MatDividerModule,
      MatPaginatorModule,
      MatSortModule,
      MatTableModule,
      MatTooltipModule,
      MatDialogModule,
      MatSnackBarModule,
      MatListModule,
      MatTreeModule,
      MatCheckboxModule,
      MatRadioModule,
      DragDropModule,
      MatExpansionModule,
      MatSlideToggleModule,
      MatTabsModule,
      MatChipsModule,
      MatProgressSpinnerModule,
   ]
})

export class MaterialModude{}
